/**
 * ui_glass_shaders.h - Mã GLSL nhúng của hiệu ứng kính.
 *
 * Nhúng thẳng vào binary thay vì đọc từ file để launcher không bao giờ
 * hỏng giao diện chỉ vì thiếu thư mục assets khi chạy ở nơi khác.
 */
#ifndef UI_GLASS_SHADERS_H
#define UI_GLASS_SHADERS_H

// Làm mờ Gauss tách trục: chạy một lần theo phương ngang, một lần theo dọc.
// Dùng thủ thuật lấy mẫu tuyến tính nên chỉ cần 5 lần texture() cho kernel 9 tap.
static const char *UI_GLASS_BLUR_FS =
"#version 330\n"
"in vec2 fragTexCoord;\n"
"in vec4 fragColor;\n"
"out vec4 finalColor;\n"
"uniform sampler2D texture0;\n"
"uniform vec2 uDir;\n"
"void main()\n"
"{\n"
"    vec4 c = texture(texture0, fragTexCoord) * 0.2270270270;\n"
"    vec2 o1 = uDir * 1.3846153846;\n"
"    vec2 o2 = uDir * 3.2307692308;\n"
"    c += (texture(texture0, fragTexCoord + o1) + texture(texture0, fragTexCoord - o1)) * 0.3162162162;\n"
"    c += (texture(texture0, fragTexCoord + o2) + texture(texture0, fragTexCoord - o2)) * 0.0702702703;\n"
"    finalColor = vec4(c.rgb, 1.0);\n"
"}\n";

// Shader kính chính.
//
// Hình dạng tấm kính là một signed distance field hình chữ nhật bo góc.
// Từ SDF ta lấy được: mặt nạ khử răng cưa, vector pháp tuyến của mép, và
// khoảng cách tới mép - ba thứ đủ để dựng khúc xạ, highlight và bóng trong.
static const char *UI_GLASS_PANEL_FS =
"#version 330\n"
"in vec2 fragTexCoord;\n"
"in vec4 fragColor;\n"
"out vec4 finalColor;\n"
"uniform sampler2D texture0;\n"
"uniform vec4 colDiffuse;\n"
"\n"
"uniform vec2  uQuadPos;\n"      // Góc trên-trái của quad đang vẽ (pixel)
"uniform vec2  uQuadSize;\n"     // Kích thước quad (pixel)
"uniform vec2  uResolution;\n"   // Kích thước canvas (pixel)
"uniform vec2  uRectCenter;\n"   // Tâm tấm kính (pixel)
"uniform vec2  uRectHalf;\n"     // Nửa kích thước tấm kính (pixel)
"uniform float uRadius;\n"
"uniform vec4  uTint;\n"         // rgb = màu phủ, a = cường độ phủ
"uniform float uRefraction;\n"
"uniform float uEdgeWidth;\n"
"uniform float uHighlight;\n"
"uniform float uInnerShadow;\n"
"uniform float uTargetLum;\n"
"uniform float uLevel;\n"
"uniform float uSaturation;\n"
"uniform float uAlpha;\n"
"uniform int   uSampleMode;\n"   // 0 = lấy mẫu nền theo toạ độ màn hình, 1 = theo UV cục bộ
"uniform int   uFlipY;\n"
"\n"
"float sdRoundBox(vec2 p, vec2 b, float r)\n"
"{\n"
"    r = min(r, min(b.x, b.y));\n"
"    vec2 q = abs(p) - b + r;\n"
"    return min(max(q.x, q.y), 0.0) + length(max(q, 0.0)) - r;\n"
"}\n"
"\n"
"void main()\n"
"{\n"
"    vec2 p = uQuadPos + fragTexCoord * uQuadSize;\n"
"    float d = sdRoundBox(p - uRectCenter, uRectHalf, uRadius);\n"
"\n"
"    // Bề rộng khử răng cưa lấy từ đạo hàm màn hình nên mép vẫn sắc\n"
"    // khi giao diện được phóng to theo kích thước cửa sổ.\n"
"    float aa = max(fwidth(d), 0.35);\n"
"    float shape = 1.0 - smoothstep(-aa, aa, d);\n"
"    if (shape <= 0.002) discard;\n"
"\n"
"    vec2 grad = vec2(dFdx(d), dFdy(d));\n"
"    vec2 n = (length(grad) > 0.00001) ? normalize(grad) : vec2(0.0, -1.0);\n"
"\n"
"    float depth = -d;\n"                                   // Khoảng cách vào phía trong
"    float edge = 1.0 - smoothstep(0.0, max(uEdgeWidth, 0.5), depth);\n"
"    edge = clamp(edge, 0.0, 1.0);\n"
"    float edgeSq = edge * edge;\n"
"\n"
"    vec2 uv;\n"
"    if (uSampleMode == 0)\n"
"    {\n"
"        vec2 sp = p - n * (uRefraction * edgeSq);\n"
"        uv = sp / uResolution;\n"
"    }\n"
"    else\n"
"    {\n"
"        uv = fragTexCoord - n * (uRefraction * edgeSq) / max(uQuadSize, vec2(1.0));\n"
"    }\n"
"    if (uFlipY == 1) uv.y = 1.0 - uv.y;\n"
"    uv = clamp(uv, vec2(0.002), vec2(0.998));\n"
"\n"
"    vec3 base = texture(texture0, uv).rgb;\n"
"\n"
"    // Vật liệu kính: chỉ kéo ĐỘ SÁNG của hậu cảnh về mức đích, còn sắc màu\n"
"    // giữ nguyên. Nhờ scale đều ba kênh nên nền trắng ra xám trung tính,\n"
"    // nền xanh ra xanh - kính không tự áp một màu nào lên giao diện.\n"
"    float lum = dot(base, vec3(0.2126, 0.7152, 0.0722));\n"
"    float target = mix(lum, uTargetLum, clamp(uLevel, 0.0, 1.0));\n"
"    vec3 col = base * (target / max(lum, 0.02));\n"
"\n"
"    // Khi phải kéo sáng mạnh, kênh màu có thể tràn và làm lệch sắc;\n"
"    // lúc đó lùi dần về xám cùng độ sáng thay vì để màu bị cháy.\n"
"    float peak = max(max(col.r, col.g), col.b);\n"
"    col = mix(col, vec3(target), clamp(peak - 1.0, 0.0, 1.0));\n"
"\n"
"    // Bù lại phần bão hoà mất đi, giống lớp vật liệu kính của Apple.\n"
"    col = clamp(mix(vec3(target), col, uSaturation), 0.0, 1.0);\n"
"\n"
"    // Màu phủ thêm: chỉ dùng cho bề mặt màu nhấn (nút bấm, mục đang chọn).\n"
"    col = mix(col, uTint.rgb, clamp(uTint.a, 0.0, 1.0));\n"
"\n"
"    // Vệt sáng đổ dần từ trên xuống, mô phỏng ánh sáng môi trường.\n"
"    float gy = clamp((p.y - (uRectCenter.y - uRectHalf.y)) / max(2.0 * uRectHalf.y, 1.0), 0.0, 1.0);\n"
"    col += vec3(0.075) * (1.0 - gy) * uHighlight;\n"
"\n"
"    // Phản sáng trên mép: mạnh nhất ở phía đối diện nguồn sáng.\n"
"    vec2 lightDir = normalize(vec2(-0.40, -1.0));\n"
"    float rim = smoothstep(2.2, 0.0, abs(d + 1.1));\n"
"    float facing = max(dot(n, -lightDir), 0.0);\n"
"    col += vec3(1.0) * rim * (0.14 + 0.62 * facing * facing) * uHighlight;\n"
"\n"
"    // Bóng trong ở mép khuất sáng, giúp tấm kính có độ dày.\n"
"    float away = max(dot(n, lightDir), 0.0);\n"
"    col -= vec3(0.10, 0.11, 0.14) * edgeSq * away * uInnerShadow;\n"
"\n"
"    float alpha = shape * uAlpha * fragColor.a * colDiffuse.a;\n"
"    finalColor = vec4(clamp(col, 0.0, 1.0), alpha);\n"
"}\n";

// Shader phụ: vẽ viền / quầng sáng bo góc mà không cần lấy mẫu nền.
static const char *UI_GLASS_STROKE_FS =
"#version 330\n"
"in vec2 fragTexCoord;\n"
"in vec4 fragColor;\n"
"out vec4 finalColor;\n"
"uniform vec4 colDiffuse;\n"
"uniform vec2  uQuadPos;\n"
"uniform vec2  uQuadSize;\n"
"uniform vec2  uRectCenter;\n"
"uniform vec2  uRectHalf;\n"
"uniform float uRadius;\n"
"uniform float uThickness;\n"
"uniform float uSpread;\n"
"uniform int   uMode;\n"          // 0 = viền, 1 = quầng sáng ngoài, 2 = bóng đổ
"uniform vec4  uColor;\n"
"\n"
"float sdRoundBox(vec2 p, vec2 b, float r)\n"
"{\n"
"    r = min(r, min(b.x, b.y));\n"
"    vec2 q = abs(p) - b + r;\n"
"    return min(max(q.x, q.y), 0.0) + length(max(q, 0.0)) - r;\n"
"}\n"
"\n"
"void main()\n"
"{\n"
"    vec2 p = uQuadPos + fragTexCoord * uQuadSize;\n"
"    float d = sdRoundBox(p - uRectCenter, uRectHalf, uRadius);\n"
    "    float aa = max(fwidth(d), 0.35);\n"
"    float a = 0.0;\n"
"    if (uMode == 0)\n"
"    {\n"
"        // Dải viền nằm gọn phía trong mép.\n"
"        a = (1.0 - smoothstep(0.0, aa * 1.4, abs(d + uThickness * 0.5) - uThickness * 0.5));\n"
"    }\n"
"    else if (uMode == 1)\n"
"    {\n"
"        // Quầng sáng: tắt dần ra ngoài, rỗng ở giữa.\n"
"        a = 1.0 - smoothstep(0.0, uSpread, max(d, 0.0));\n"
"        a *= a;\n"
"        a *= smoothstep(-2.0, 1.0, d);\n"
"    }\n"
"    else\n"
"    {\n"
"        // Bóng đổ mềm phía dưới tấm kính.\n"
"        a = 1.0 - smoothstep(0.0, uSpread, max(d, 0.0));\n"
"        a = pow(a, 1.6);\n"
"    }\n"
"    if (a <= 0.003) discard;\n"
"    finalColor = vec4(uColor.rgb, uColor.a * a * fragColor.a * colDiffuse.a);\n"
"}\n";

#endif // UI_GLASS_SHADERS_H
